### ISSUE TITLE
HIgh contrast of the imported images

### ISSUE THREAD

**Issue by dkapiton** [hssm/media-import#15]
Thank you for this awesome add-on, however, when using this media-import add-on, images are of much higher contrast than the original. It has to do something with the import (compression?), dragging snapshots into flashcard retains original image colors. Changing card style did not fix the issue
![Screen Shot 2020-10-21 at 12 29 31 AM](https://user-images.githubusercontent.com/73218121/96685583-9001cc80-133a-11eb-905a-93a6679c2327.png)
![Screen Shot 2020-10-21 at 12 30 50 AM](https://user-images.githubusercontent.com/73218121/96685591-93955380-133a-11eb-9af2-6352f886c593.png)
Thank you very much for your help!

**Comment by hssm** [comment]
The add-on doesn't perform any kind of processing on the media you import. It uses the exact same function that Anki itself uses when you drag+drop images onto a flashcard. There must be something in the card template that is causing this issue, but without seeing it and without a test case I can't really offer any advice.

**Comment by dkapiton** [comment]
Thank you very much, Houssam, for the outstanding add-on to Anki, it has
the potential to revolutionize bio-medical education. Especially subjects
like histology, which is image-based education.
I found what the issue was: when a jpg image is saved in CMYK color, it is
imported into Anki with high contrast and colors are screwed up. When it is
in RGB, color reproduction is perfect. I didn't realise that the images I
am importing are in CMYK.
Thank you very much!

**Comment by hssm** [comment]
Great, glad you found a solution to the problem.
