### ISSUE TITLE
Image Path

### ISSUE THREAD

**Issue by DrLulz** [hssm/media-import#2]
I'm using colorbox (jQuery plugin) and it requires image paths. Would you happen to know how anki displays the images in the fields, and possible how I could add a class to that element? Everything is working except it would be a pain to write out paths for each image.

I've tried the below with no success.

````
<script>
$('img').each(function(){
	$(this).attr('class', 'gallery');
});
jQuery('a.gallery').colorbox();
</script>
```

**Comment by hssm** [comment]
Are you trying to use colobox in the reviewer or somewhere else? What you've done will work in the reviewer, but you don't get javascript or jquery access anywhere else.

Also you should append to the class instead of replacing it since you will overwrite any classes that some images use (the `marked` icon in particular).

**Comment by DrLulz** [comment]
In the reviewer. Thanks for pointing out the class addition.

In the below example the bottom image is doing what I want, however, the top image (from `{{Front}}`) is not getting wrapped. 

Does Anki display images from fields as `<img src="image.png"></img>`?

My Front Template:
````
<link type="text/css" rel="stylesheet" href="colorbox/colorbox.css" />
<script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
<script type="text/javascript" src="colorbox/jquery.colorbox-min.js"></script>

<script>
$("img").each(function() {
    var $this = $(this);
    var src = $this.attr('src');
    var a = $('<a/>').attr('href', src).attr('class', 'gallery');
    $this.wrap(a);
});
</script>

{{Front}}

<br />
<a class='gallery' href='image.png' title='IMAGE'><img src='image.png'></img></a>


<script>
	jQuery('a.gallery').colorbox();
</script>
```

**Comment by hssm** [comment]
Mostly, just without the closing tag:
```<img src="apple.jpg">```

You can add ```alert(document.body.innerHTML);``` to see what the card HTML is when the reviewer loads it. Not the best way to debug but it gives you something to work with. Your code produces this, which is almost exactly like your example line:

```
<div id="qa"><style>.card {
 font-family: arial;
 font-size: 20px;
 text-align: center;
 color: black;
 background-color: white;
}
</style><a href="apple.jpg" class="gallery"><img src="apple.jpg"></a>
</div>
```

**Comment by DrLulz** [comment]
The `alert(document.body.innerHTML);` shows that my image tag is not being wrapped. hmm... I wonder why yours is wrapping.

**Comment by DrLulz** [comment]
Thank you for the help. I got it working with this. Not sure why the other wasn't doing it.

````
<link type="text/css" rel="stylesheet" href="colorbox/colorbox.css" />
<script type="text/javascript" src="js/jquery-1.11.2.min.js"></script>
<script type="text/javascript" src="colorbox/jquery.colorbox-min.js"></script>


{{Front}}


<script>
$("img").each(function() {
    var $this = $(this);
    var src = $this.attr('src');
    var a = $('<a/>').attr('href', src).attr('class', 'gallery');
    $this.wrap(a);
});
jQuery('a.gallery').colorbox();
</script>
```
