### ISSUE TITLE
Split filename

### ISSUE THREAD

**Issue by nicolas-raoul** [hssm/media-import#6]
It would be wonderful if I could specify a field via the filename.

I have a folder that contains hundreds of images of molecules suffixed with the lesson they were introduced at:

```
3-methyl-1-butyn-3-ol.chapter17lesson3.png
2-Ethyl Hexanol.chapter17lesson4.png
Butan-1-ol.chapter17lesson4.png
Diethylbenzene.chapter17lesson3.png
Isopropanol.chapter17lesson5.png
Sodium thiosulfate.chapter17lesson3.png
Oxyalkylated alkylphenol.chapter17lesson4.png
```

It would be great if the `chapter17lesson3` could be used by itself as a field, it would make it easy to unsuspend a particular lesson for instance.

The UI would become a bit more complex, admittedly, but if limited to a single sub-extension it should not be that bad (I mean, not handling `name.subextension1.subextension2.extension`)

Cheers! :-)

**Comment by hssm** [comment]
I added an `Extension-1` option so you can do this. 

Only catch is that I've ported the add-on to Anki 2.1 and don't intend to support earlier versions. So you can either transfer the (tiny) changes to your copy of the add-on or grab an alpha build of Anki 2.1 to run the import.

**Comment by nicolas-raoul** [comment]
Wonderful, that works!
Sorry for asking that much, but would the following be possible?

When the sub-extension is used, remove it from the filename.

Example for `Sodium thiosulfate.chapter17lesson3.png`:
- Filename: `Sodium thiosulfate`
- Sub-extension: `chapter17lesson3`
Currently, the Filename is `Sodium thiosulfate.chapter17lesson3`.

**Comment by hssm** [comment]
I feel like it would be unintuitive to have one field modify another field by having it selected.

I think this use-case is very limited and probably isn't worth adding to the main add-on. It's sorta semi-official so I don't want to keep adding little things to clutter it up.
