### ISSUE TITLE
Output to a tag

### ISSUE THREAD

**Issue by nicolas-raoul** [hssm/media-import#7]
It would be great if I could output a field to be used as a tag.

In this example:
```
3-methyl-1-butyn-3-ol.chapter17lesson3.png
2-Ethyl Hexanol.chapter17lesson4.png
Butan-1-ol.chapter17lesson4.png
Diethylbenzene.chapter17lesson3.png
Isopropanol.chapter17lesson5.png
Sodium thiosulfate.chapter17lesson3.png
Oxyalkylated alkylphenol.chapter17lesson4.png
```
... the tags `chapter17lesson3`, `chapter17lesson4`, `chapter17lesson5` would be created and assigned to the relevant notes.

My current workaround is to use a hidden field dedicated to that purpose.

A drawback is that it makes the UI more cluttered, and beginners might not realize that they are allowed to leave it empty.

**Comment by hssm** [comment]
Adding to tags makes a lot of sense. I don't know why I didn't include it originally. Should be simple enough.

**Comment by hssm** [comment]
I've pushed a change that supports this now.

**Comment by nicolas-raoul** [comment]
Wonderful, thanks!
I `git pulled` and replaced the plugin in my addons21, but somehow the UI does not seem to have changed? Below is an example of how I imagined it could look like, am I mistaken entirely?
![tag](https://cloud.githubusercontent.com/assets/99590/16871326/44abac42-4ac1-11e6-8fe0-ceeb1fe39136.png)

**Comment by hssm** [comment]
That's exactly what it's meant to look like. Try deleting any leftover .pyc files if there are any.

**Comment by nicolas-raoul** [comment]
I forgot to report that it works great, thanks :-)
I indeed had some leftovers.
