### ISSUE TITLE
Addon scales images

### ISSUE THREAD

**Issue by redlap2** [hssm/media-import#9]
Hi, I wanted to import a folder of book pages, to make sure I do all of them.

I got scaled down images on Anki with unreadable text.

Is it possible to add an option to NOT rescale image, otherwise I can't use it. :)

Thanks

**Comment by hssm** [comment]
Image scaling is not part of the add-on but a built-in feature of Anki.

You can override it by adding this line to the `styling` section of your card template:

```
img {max-width: initial; max-height: initial;}
```
